<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="NewUpdatingProduct.aspx.cs" Inherits="Program4.NewUpdatingProduct" %>

<!DOCTYPE html>
<head>
    <title>UWP - CS3870 : First Program</title>
	<link rel="stylesheet" type="text/css" href= "StyleSheet1.css" />

    <style type="text/css">
        .auto-style1 {
            margin-left: 309px;
        }
    </style>

</head>

<body>

	<form id="form1" runat="server">

	<h1 class="CS3870Title">Web Protocols, Technologies and Applications </h1> 
	<h2 class="Name">Andre Sandoval</h2>


    <ul class="navbar">
        <li> <a href="MasterPage.aspx">All Products </a></li>

        <li> <a href="NewUpdatingProduct.aspx">Updating Products </a></li>

        <li> <a href="Shopping.aspx">Shopping </a></li>

    </ul>
	
    <h3 class="center">Prog 4</h3>

              <br />
              <br />

    <p class="centerText">



        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Prog4DatabaseConnectionString %>" SelectCommand="SELECT * FROM [product]" DeleteCommand="DELETE FROM [product] WHERE [ProductID] = @ProductID" InsertCommand="INSERT INTO [product] ([ProductID], [ProductName], [UnitPrice], [Description] ) VALUES(@ProductID, @ProductName, @UnitPrice, @Description)" OnSelecting="SqlDataSource1_Selecting" UpdateCommand="UPDATE [Product] SET ProductName = @ProductName, UnitPrice = @UnitPrice, Description = @Description WHERE ProductID = @ProductID"></asp:SqlDataSource>
        <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateRows="False" CssClass="auto-style1" DataKeyNames="ProductID" DataSourceID="SqlDataSource1" Height="113px" Width="403px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" OnPageIndexChanging="DetailsView1_PageIndexChanging">
            <Fields>
                <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" SortExpression="ProductID" />
                <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            </Fields>
            <PagerSettings FirstPageText="First" LastPageText="Last " Mode="NextPreviousFirstLast" NextPageText="Next " PreviousPageText="Previous" />
        </asp:DetailsView>
    </form>



</body>
</html>
